const salarySetupData = {
  employee: {
    name: "Professor Dr. Md. Arafat Baset",
    designation: "Vice-Chancellor",
    department: "Secretariat of the VC",
    joiningDate: "23 Mar 2021",
    employeeId: "11001",
    basePay: "78000",
    bankAccount: "01207429990",
    date: "Sep 2024",
  },
  allowances: [
    {
      no: 1,
      name: "Basic Pay",
      currentAmount: "78000",
      arrearAmount: "0",
      total: "78000",
      ruleOver: false,
      comments: "Comment",
    },
    {
      no: 2,
      name: "Festival Allowance",
      currentAmount: "0",
      arrearAmount: "0",
      total: "0",
      ruleOver: false,
      comments: "Comment",
    },
    {
      no: 3,
      name: "Personal Pay",
      currentAmount: "0",
      arrearAmount: "0",
      total: "0",
      ruleOver: false,
      comments: "Comment",
    },
  ],
  deductions: [
    {
      no: 1,
      name: "PF Contribution",
      currentAmount: "0",
      arrearAmount: "0",
      total: "0",
      ruleOver: false,
      comments: "Comment",
    },
    {
      no: 2,
      name: "Benevolent Fund",
      currentAmount: "0",
      arrearAmount: "0",
      total: "0",
      ruleOver: false,
      comments: "Comment",
    },
    {
      no: 3,
      name: "Group Insurance Premium",
      currentAmount: "0",
      arrearAmount: "0",
      total: "0",
      ruleOver: false,
      comments: "Comment",
    },
  ],
  totals: {
    subTotal: 12610,
    netTotal: 12610,
    arrear: "0",
  },
};

export default salarySetupData;
