import { NavItem } from "@/types";
import {
  AlignEndVertical,
  Blinds,
  BookOpenCheck,
  BriefcaseBusiness,
  Building,
  CalendarCheck2,
  Captions,
  ClipboardType,
  Clock,
  Disc,
  Fan,
  FileBadge2,
  LayoutDashboard,
  NotebookText,
  PlayIcon,
  ScrollText,
  Settings,
  Soup,
  SquarePen,
  UserRoundCog,
  UserRoundSearch,
  Users,
  Vote,
} from "lucide-react";

const hrmNavItems: NavItem[] = [
  {
    title: "Dashboard",
    icon: LayoutDashboard,
    href: "/hrm",
    color: "text-sky-500",
    permissions: ["hrm"],
  },
  {
    title: "Employee",
    icon: Users,
    href: "/hrm",
    color: "text-sky-500",
    permissions: ["hrm"],
    isChildren: true,
    children: [
      {
        title: "Employee List",
        icon: BookOpenCheck,
        color: "text-sky-500",
        href: "/hrm/employees-list",
        permissions: ["hrm"],
      },

      {
        title: "Employee Classes",
        icon: Fan,
        href: "/hrm/employee-classes",
        color: "text-sky-500",
        permissions: ["hrm"],
      },
      {
        title: "Employee Grades",
        icon: Blinds,
        href: "/hrm/employee-grades",
        color: "text-sky-500",
        permissions: ["hrm"],
      },
    ],
  },

  {
    title: "Attendance",
    icon: CalendarCheck2,
    href: "/hrm",
    color: "text-sky-500",
    permissions: ["hrm"],
    isChildren: true,
    children: [
      {
        title: "Attendances List",
        icon: PlayIcon,
        href: "/hrm/attendances-list",
        color: "text-sky-500",
        permissions: ["hrm"],
      },

      {
        title: "Daily Attendance",
        icon: CalendarCheck2,
        color: "text-sky-500",
        href: "/hrm/daily-attendance",
        permissions: ["hrm"],
      },
      {
        title: "Schedules",
        icon: Clock,
        href: "/hrm/schedules",
        color: "text-sky-500",
        permissions: ["hrm"],
      },
      {
        title: "Roster",
        icon: ScrollText,
        href: "/hrm/rosters",
        color: "text-sky-500",
        permissions: ["hrm"],
      },
      {
        title: "Roster Employee",
        icon: Soup,
        href: "/hrm/roster-employee",
        color: "text-sky-500",
        permissions: ["hrm"],
      },
      {
        title: "Attendance PM",
        icon: PlayIcon,
        href: "/hrm/attendance-policy-mapping",
        color: "text-sky-500",
        permissions: ["hrm"],
      },
    ],
  },

  {
    title: "Leave",
    icon: Clock,
    href: "/hrm",
    color: "text-sky-500",
    permissions: ["hrm"],
    isChildren: true,
    children: [
      {
        title: "Leave Request",
        icon: Clock,
        href: "/hrm/leave-request",
        color: "text-sky-500",
        permissions: ["hrm"],
      },
      {
        title: "Leave Type",
        icon: Clock,
        href: "/hrm/leave-type",
        color: "text-sky-500",
        permissions: ["hrm"],
      },
      {
        title: "Leave Group",
        icon: Clock,
        href: "/hrm/leave-group",
        color: "text-sky-500",
        permissions: ["hrm"],
      },
      {
        title: "Holiday",
        icon: Soup,
        href: "/hrm/holidays",
        color: "text-sky-500",
        permissions: ["hrm"],
      },
    ],
  },

  {
    title: "Salary",
    icon: CalendarCheck2,
    href: "/hrm",
    color: "text-sky-500",
    permissions: ["hrm"],
    isChildren: true,
    children: [
      {
        title: "Employee Payslip",
        icon: CalendarCheck2,
        color: "text-sky-500",
        href: "/hrm/employee-salary-payslip",
        permissions: ["hrm"],
      },
      {
        title: "Bank Salary Advice",
        icon: CalendarCheck2,
        color: "text-sky-500",
        href: "/hrm/bank-salary-advice",
        permissions: ["hrm"],
      },
      {
        title: "Salary Breakup",
        icon: CalendarCheck2,
        color: "text-sky-500",
        href: "/hrm/salary_breakup",
        permissions: ["hrm"],
      },

      {
        title: "Salary Certificate",
        icon: CalendarCheck2,
        color: "text-sky-500",
        href: "/hrm/salary-certificate",
        permissions: ["hrm"],
      },
      {
        title: "Salary Sheet",
        icon: CalendarCheck2,
        color: "text-sky-500",
        href: "/hrm/salary-sheet",
        permissions: ["hrm"],
      },
      {
        title: "Salary Setup",
        icon: CalendarCheck2,
        color: "text-sky-500",
        href: "/hrm/salary-setup",
        permissions: ["hrm"],
      },

      {
        title: "Estimate Salary",
        icon: CalendarCheck2,
        color: "text-sky-500",
        href: "/hrm/estimate-salary",
        permissions: ["hrm"],
      },
    ],
  },

  {
    title: "Provident Fund",
    icon: Captions,
    href: "/hrm/new-route",
    color: "text-sky-500",
    permissions: ["hrm"],
  },

  {
    title: "Tax",
    icon: ClipboardType,
    href: "/hrm/new-route",
    color: "text-sky-500",
    permissions: ["hrm"],
  },

  {
    title: "Policies",
    icon: Vote,
    href: "/hrm",
    color: "text-sky-500",
    permissions: ["hrm"],
    isChildren: true,
    children: [
      {
        title: "Attendance Policy",
        icon: PlayIcon,
        href: "/hrm/attendance-policy",
        color: "text-sky-500",
        permissions: ["hrm"],
      },
      {
        title: "Leave Policy",
        icon: SquarePen,
        href: "/hrm/leave-policy",
        color: "text-sky-500",
        permissions: ["hrm"],
      },
      {
        title: "Over Time Policy",
        icon: SquarePen,
        href: "/hrm/overtime-policy",
        color: "text-sky-500",
        permissions: ["hrm"],
      },
      {
        title: "Deduction Policy",
        icon: SquarePen,
        href: "/hrm/deduction-policy",
        color: "text-sky-500",
        permissions: ["hrm"],
      },
    ],
  },

  {
    title: "Recruitment",
    icon: UserRoundSearch,
    href: "hrm/new-route",
    color: "text-sky-500",
    permissions: ["hrm"],
  },

  {
    title: "Reports",
    icon: NotebookText,
    href: "/hrm",
    color: "text-sky-500",
    permissions: ["hrm"],
    isChildren: true,
    children: [
      {
        title: "Leave Summary",
        icon: UserRoundSearch,
        href: "leave-summary",
        color: "text-sky-500",
        permissions: ["hrm"],
      },
      {
        title: "Leave Usages",
        icon: UserRoundSearch,
        href: "leave-usages",
        color: "text-sky-500",
        permissions: ["hrm"],
      },
      {
        title: "Leave Balance",
        icon: UserRoundSearch,
        href: "leave-balance",
        color: "text-sky-500",
        permissions: ["hrm"],
      },
      {
        title: "Leave Trend",
        icon: UserRoundSearch,
        href: "leave-trend",
        color: "text-sky-500",
        permissions: ["hrm"],
      },
      {
        title: "Leave Type Summary",
        icon: UserRoundSearch,
        href: "leave-type-summary",
        color: "text-sky-500",
        permissions: ["hrm"],
      },
    ],
  },

  {
    title: "Catalog",
    icon: Captions,
    href: "/hrm",
    color: "text-sky-500",
    permissions: ["hrm"],
    isChildren: true,
    children: [
      {
        title: "Departments",
        icon: Building,
        href: "/hrm/departments",
        color: "text-sky-500",
        permissions: ["hrm"],
      },
      {
        title: "Designations",
        icon: FileBadge2,
        href: "/hrm/designations",
        color: "text-sky-500",
        permissions: ["hrm"],
      },
      {
        title: "Sections",
        icon: AlignEndVertical,
        href: "/hrm/sections",
        color: "text-sky-500",
        permissions: ["hrm"],
      },
    ],
  },

  {
    title: "Job",
    href: "/hrm",
    icon: BriefcaseBusiness,
    color: "text-sky-500",
    permissions: ["hrm"],
    isChildren: true,
    children: [
      {
        title: "Vacancy Requisition",
        icon: Disc,
        href: "/hrm/vacancy-requisitions",
        color: "text-sky-500",
        permissions: ["hrm"],
      },
      {
        title: "Job Posts",
        icon: SquarePen,
        href: "/hrm/job-posts",
        color: "text-sky-500",
        permissions: ["hrm"],
      },
      {
        title: "Job Candidates",
        icon: UserRoundCog,
        href: "/hrm/job-candidates",
        color: "text-sky-500",
        permissions: ["hrm"],
      },
      {
        title: "Job Apply",
        icon: BriefcaseBusiness,
        href: "/hrm/job-apply",
        color: "text-sky-500",
        permissions: ["hrm"],
      },
    ],
  },

  {
    title: "HRM Setting",
    icon: Settings,
    href: "hrm/new-route",
    color: "text-sky-500",
    permissions: ["hrm"],
  },
];

export default hrmNavItems;
