name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Agrovet VPS via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 103.132.218.15
          username: akaarit2
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/asbd-agrovet/htdocs/agrovet-erp-frontend;
            git config --global --add safe.directory /home/runner/work/agrovet-erp-frontend/agrovet-erp-frontend/
            git pull origin main